# DB datasource
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/food-app-db
    username: sa
    password:
    driver-class-name: org.h2.Driver

# h2
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  sql:
#    init:
#      mode: always
# JPA

  jpa:
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.H2Dialect
    database: h2
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /api/v1/**

# Kakao Login
oauth2:
 kakao:
    client-id: 00bc98205fb1398ae66fa17556a3d66e
    client-secret: JHIU3z5KdxAYX4dmNWFxbGCzrG5DzCf1
    redirect-uri: http://localhost:8080/login/oauth2/code/kakao

    provider:
      kakao:
        #authorization-uri: https://kauth.kakao.com/oauth/authorize
        token-uri: https://kauth.kakao.com/oauth/token
        user-info-uri: https://kapi.kakao.com/v2/user/me
        #user-name-attribute: id

jwt:
  secret: SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJVadQssw5cflKxwRJSMeKKF2QT4fwpMeJf36POk6yJVadQssw5c

oauth:
  secret: HIU3z5KdxAYX4dmNWFxbGCzrG5DzCf1
#  app-key: 45684b869b225c4ea5c773d0419d6584
  api-key: 00bc98205fb1398ae66fa17556a3d66e
  uri:
    iss-uri: https://kauth.kakao.com
    public-key-uri: https://kauth.kakao.com/.well-known/jwks.json

