# DB datasource
spring:
  datasource:
    url: jdbc:h2:~/food-app-db
    username: sa
    password:
    driver-class-name: org.h2.Driver
# h2
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
# JPA
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.H2Dialect
    database: h2
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /api/v1/**